# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OboardCamDisp1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SettingsFm = QtWidgets.QFrame(self.frame)
        self.SettingsFm.setMinimumSize(QtCore.QSize(400, 0))
        self.SettingsFm.setMaximumSize(QtCore.QSize(400, 16777215))
        self.SettingsFm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SettingsFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SettingsFm.setObjectName("SettingsFm")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.SettingsFm)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.SettingsFm)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_6.setHorizontalSpacing(1)
        self.gridLayout_6.setVerticalSpacing(2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.FilePathLb = QtWidgets.QLabel(self.frame_5)
        self.FilePathLb.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.FilePathLb.setObjectName("FilePathLb")
        self.gridLayout_6.addWidget(self.FilePathLb, 2, 0, 1, 1)
        self.FilePathLE = QtWidgets.QLineEdit(self.frame_5)
        self.FilePathLE.setReadOnly(True)
        self.FilePathLE.setObjectName("FilePathLE")
        self.gridLayout_6.addWidget(self.FilePathLE, 2, 2, 1, 1)
        self.FilePathBt = QtWidgets.QPushButton(self.frame_5)
        self.FilePathBt.setMaximumSize(QtCore.QSize(60, 30))
        self.FilePathBt.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.FilePathBt.setObjectName("FilePathBt")
        self.gridLayout_6.addWidget(self.FilePathBt, 2, 3, 1, 1)
        self.ColorFm = QtWidgets.QFrame(self.frame_5)
        self.ColorFm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ColorFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ColorFm.setObjectName("ColorFm")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ColorFm)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.GrayImgCkB = QtWidgets.QCheckBox(self.ColorFm)
        self.GrayImgCkB.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.GrayImgCkB.setObjectName("GrayImgCkB")
        self.gridLayout_7.addWidget(self.GrayImgCkB, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.ColorFm, 0, 0, 2, 4)
        self.gridLayout_5.addWidget(self.frame_5, 0, 1, 1, 3)
        self.EmptyFm = QtWidgets.QFrame(self.SettingsFm)
        self.EmptyFm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.EmptyFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.EmptyFm.setObjectName("EmptyFm")
        self.gridLayout_5.addWidget(self.EmptyFm, 1, 1, 4, 3)
        self.gridLayout_2.addWidget(self.SettingsFm, 0, 0, 1, 1)
        self.DispFm = QtWidgets.QFrame(self.frame)
        self.DispFm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.DispFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.DispFm.setObjectName("DispFm")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.DispFm)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ShowBt = QtWidgets.QPushButton(self.DispFm)
        self.ShowBt.setObjectName("ShowBt")
        self.gridLayout_3.addWidget(self.ShowBt, 0, 0, 1, 1)
        self.ExitBt = QtWidgets.QPushButton(self.DispFm)
        self.ExitBt.setObjectName("ExitBt")
        self.gridLayout_3.addWidget(self.ExitBt, 0, 3, 1, 1)
        self.StopBt = QtWidgets.QPushButton(self.DispFm)
        self.StopBt.setObjectName("StopBt")
        self.gridLayout_3.addWidget(self.StopBt, 0, 1, 1, 1)
        self.RecordBt = QtWidgets.QPushButton(self.DispFm)
        self.RecordBt.setObjectName("RecordBt")
        self.gridLayout_3.addWidget(self.RecordBt, 0, 2, 1, 1)
        self.DispLb = QtWidgets.QLabel(self.DispFm)
        self.DispLb.setText("")
        self.DispLb.setScaledContents(True)
        self.DispLb.setObjectName("DispLb")
        self.gridLayout_3.addWidget(self.DispLb, 1, 0, 1, 4)
        self.VideoInfoFm = QtWidgets.QFrame(self.DispFm)
        self.VideoInfoFm.setMaximumSize(QtCore.QSize(16777215, 60))
        self.VideoInfoFm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VideoInfoFm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoInfoFm.setObjectName("VideoInfoFm")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.VideoInfoFm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.VideoInfoFm)
        self.label.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.FmRateLCD = QtWidgets.QLCDNumber(self.VideoInfoFm)
        self.FmRateLCD.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FmRateLCD.setObjectName("FmRateLCD")
        self.horizontalLayout.addWidget(self.FmRateLCD)
        self.label_2 = QtWidgets.QLabel(self.VideoInfoFm)
        self.label_2.setStyleSheet("font: 11pt \"Adobe 黑体 Std R\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.ImgWidthLCD = QtWidgets.QLCDNumber(self.VideoInfoFm)
        self.ImgWidthLCD.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ImgWidthLCD.setObjectName("ImgWidthLCD")
        self.horizontalLayout.addWidget(self.ImgWidthLCD)
        self.ImgHeightLCD = QtWidgets.QLCDNumber(self.VideoInfoFm)
        self.ImgHeightLCD.setObjectName("ImgHeightLCD")
        self.horizontalLayout.addWidget(self.ImgHeightLCD)
        self.gridLayout_3.addWidget(self.VideoInfoFm, 4, 0, 1, 4, QtCore.Qt.AlignLeft)
        self.gridLayout_2.addWidget(self.DispFm, 0, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.MsgTE = QtWidgets.QTextEdit(self.frame_4)
        self.MsgTE.setReadOnly(True)
        self.MsgTE.setObjectName("MsgTE")
        self.gridLayout_4.addWidget(self.MsgTE, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FilePathLb.setText(_translate("MainWindow", "存储路径："))
        self.FilePathBt.setText(_translate("MainWindow", "…"))
        self.GrayImgCkB.setText(_translate("MainWindow", "使用yolov3-tiny"))
        self.ShowBt.setText(_translate("MainWindow", "开始"))
        self.ExitBt.setText(_translate("MainWindow", "退出"))
        self.StopBt.setText(_translate("MainWindow", "暂停"))
        self.RecordBt.setText(_translate("MainWindow", "保存"))
        self.label.setText(_translate("MainWindow", "当前帧频："))
        self.label_2.setText(_translate("MainWindow", "图像尺寸："))

